In [184]:
import pandas as pd
import numpy as np
import time
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models, utils
import matplotlib.pyplot as plt
from skimage import io, transform
from PIL import Image
from os import path
import copy
import chexpert as chx
from importlib import reload
import itertools
reload(chx)
# %matplotlib inline

<module 'chexpert' from '/Users/habbes/code/class/bd4h/chexpert/chexpert.py'>

In [185]:
trainer = chx.Trainer(max_train_samples=150)

/Users/habbes/anaconda3/lib/python3.6/site-packages/torchvision/models/densenet.py:212: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)


In [ ]:
trainer.train()

Epoch 0/2
----------


In [111]:
torch.sum(torch.tensor([1, 2]))

tensor(3)

In [144]:
torch.from_numpy(np.array([1.0, 0.0]).astype(np.float32)).type()

'torch.FloatTensor'

In [120]:
df= pd.read_csv('../homework5/data/seizure/seizure_validation.csv')
df.head()

X1   X2  X3   X4   X5    X6   X7   X8   X9  X10 ...  X170  X171  X172  \
0 -113  -92 -67  -37   24    63   85   62    9  -24 ...    22    19    17   
1  518  352 -94 -530 -938 -1003 -788 -300  291  831 ...  -757    19   413   
2   39   22  17  -13  -45   -63  -74  -92  -79  -87 ...   108   101    80   
3    8   31 -25  -57  -85   -87  -58  -40  -25  -33 ...  -103   -72   -65   
4  -41  -58 -89  -90  -91   -77  -40  -47  -18   26 ...    42    25    -6   

   X173  X174  X175  X176  X177  X178  y  
0    10    16     5    45    75   102  5  
1   628   607   364  -108  -661 -1091  1  
2    88    87    91   110   112   124  2  
3   -40   -69   -44   -35    22    17  3  
4   -37   -56   -76   -98   -99   -99  4  

[5 rows x 179 columns]

In [125]:
df['y'].values

array([5, 1, 2, ..., 5, 1, 2])

In [133]:
torch.double

torch.float64

In [135]:
torch.float64 == np.float64

False

In [159]:
ds = chx.get_dataset('train')

In [160]:
ld = chx.get_loader(ds)

In [165]:
inputs, labels = next(iter(ld))
inputs, labels

(tensor([[[[-2.0837, -2.0837, -2.0665,  ...,  0.4679,  0.3138,  0.2111],
           [-2.0837, -2.0837, -2.0665,  ...,  0.3481,  0.2967,  0.2624],
           [-2.0665, -2.0665, -2.0494,  ...,  0.1597,  0.2624,  0.3481],
           ...,
           [ 0.7591,  0.8618,  1.0159,  ..., -0.1657, -0.0801, -0.0287],
           [ 0.9474,  0.9303,  0.8961,  ..., -0.1486, -0.1143, -0.0972],
           [ 1.0673,  0.9646,  0.8276,  ..., -0.1486, -0.1486, -0.1486]],
 
          [[-2.0007, -2.0007, -1.9832,  ...,  0.6078,  0.4503,  0.3452],
           [-2.0007, -2.0007, -1.9832,  ...,  0.4853,  0.4328,  0.3978],
           [-1.9832, -1.9832, -1.9657,  ...,  0.2927,  0.3978,  0.4853],
           ...,
           [ 0.9055,  1.0105,  1.1681,  ..., -0.0399,  0.0476,  0.1001],
           [ 1.0980,  1.0805,  1.0455,  ..., -0.0224,  0.0126,  0.0301],
           [ 1.2206,  1.1155,  0.9755,  ..., -0.0224, -0.0224, -0.0224]],
 
          [[-1.7696, -1.7696, -1.7522,  ...,  0.8274,  0.6705,  0.5659],
           [-

In [167]:
outputs = trainer.model(inputs)

In [182]:
torch.max(outputs, 1)[1]

torch.Size([64])

In [176]:
outputs

tensor([[-0.1343,  0.1926, -0.7300, -0.7543,  0.1350],
        [-0.5216,  0.4103, -0.7358, -0.7489, -0.1542],
        [-0.4327,  0.0053, -0.5838, -0.3947,  0.3429],
        [-0.2684,  0.5591, -0.7410, -1.1276,  0.4222],
        [-0.6270, -0.2883, -0.4439, -0.8313,  0.1993],
        [ 0.2347, -0.0980, -1.2699, -0.5539,  0.2700],
        [-0.1993,  0.0391, -0.6326, -1.0168, -0.1493],
        [-0.5907, -0.1854, -0.8506, -0.4637,  0.2254],
        [ 0.0048,  0.0030, -0.4103, -0.4709, -0.2395],
        [-0.2148, -0.0688, -0.3852, -0.6397,  0.1322],
        [-0.4969, -0.3181, -0.1370, -0.9742,  0.0767],
        [-0.2109, -0.3962, -0.1546, -1.1752,  0.0345],
        [-0.3493, -0.3339, -0.4308, -0.6419,  0.3771],
        [-0.3641,  0.2698, -0.9372, -0.4296, -0.1129],
        [-0.2407,  0.3331, -0.3983, -0.7008,  0.2080],
        [-0.0714, -0.4958, -0.6387,  0.0702,  0.4726],
        [-0.5616, -0.3481, -0.3049, -0.9757,  0.1326],
        [-0.6327, -0.0929, -0.3198, -0.5121,  0.5521],
        [-

In [183]:
labels.data

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 1.],
        [0., 1., 0., 1., 1.],
        [0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0